/*

TODO: Review the UNIQUE INDEX on StudyDayNotes (idx_u_FK_to_TimelineItem). It has different NULL behavior vs. the
SQL Server version. SQL Server treats NULLs as equal in unique indexes (only one NULL combo allowed); PostgreSQL
treats NULLs as always distinct (multiple identical NULL combos allowed). You can match SQL Server semantics with
NULLS NOT DISTINCT.

 */

-- Create schema, tables, indexes, and constraints used for Snprc_scheduler module here
-- All SQL VIEW definitions should be created in snprc_scheduler-create.sql and dropped in snprc_scheduler-drop.sql
CREATE SCHEMA snprc_scheduler;

/************************************************************************
Create schema
Timeline,
TimelineItem,
Schedule,
TimelineAnimalJunction,
TimelinePojectItem


Do not have date bound reference from Timeline to TimelineAnimalJunction
Do not have date bound reference TimelineAnimalJunction to studyDataset_..._assignments


srr 10.30.18

Added qc and revisionNum columns
srr 11.01.2018

refactor keys, qcstate only in timeline.
pulled container from all tables

Changed FK to snd.Projects back to composite.
Dropped ProjectObjectId from Timeline table.
srr 11.07.2018

************************************************************************/



/*==============================================================*/
/* Table: Timeline                                              */
/*==============================================================*/
CREATE TABLE snprc_scheduler.Timeline (
  TimelineId           int                  not null,
  RevisionNum          int                  not null,
  ProjectObjectId      ENTITYID             not null,
  StartDate            date                 null,
  EndDate              date                 null,
  Description          varchar(255)         null,
  LeadTech             varchar(50)          null,
  Notes                text                 null,
  SchedulerNotes       varchar(500)         null,
  QcState              int                  null,
  Created              timestamp            null,
  CreatedBy            int                  null,
  Modified             timestamp            null,
  ModifiedBy           int                  null,
  ObjectId             ENTITYID             not null
);

COMMENT ON TABLE snprc_scheduler.Timeline IS 'Data Dict';

COMMENT ON COLUMN snprc_scheduler.Timeline.Notes IS 'Added during 9/17/18 meeting. Size TBD';

COMMENT ON COLUMN snprc_scheduler.Timeline.QcState IS 'Will handle isActive function';


ALTER TABLE snprc_scheduler.Timeline
  ADD CONSTRAINT PK_Timeline PRIMARY KEY (TimelineId, RevisionNum);

ALTER TABLE snprc_scheduler.Timeline
  ADD CONSTRAINT AK_TimelineObjectId UNIQUE (ObjectId);



/*==============================================================*/
/* Index: IDX_TimelineFK1                                       */
/*==============================================================*/
CREATE INDEX IDX_TimelineFK1 ON snprc_scheduler.Timeline (
  ProjectObjectId ASC
);

ALTER TABLE snprc_scheduler.Timeline
  ADD CONSTRAINT FK_Timeline_SNDProject FOREIGN KEY (ProjectObjectId)
REFERENCES snd.projects (Objectid);





-- %%  111111111111  %%%%%  end timeline


/*==============================================================*/
/* Table: TimelineItem       2                                   */
/*==============================================================*/
CREATE TABLE snprc_scheduler.TimelineItem (
  TimelineItemId       integer GENERATED BY DEFAULT AS IDENTITY,
  ProjectitemId        int                  not null,
  TimelineObjectId     ENTITYID             not null,
  StudyDay             int                  null,
  ScheduleDay          int                  null,
  Created              timestamp            null,
  CreatedBy            int                  null,
  Modified             timestamp            null,
  ModifiedBy           int                  null,
  ObjectId             ENTITYID             not null
);

ALTER TABLE snprc_scheduler.TimelineItem
  ADD CONSTRAINT PK_TimelineItem PRIMARY KEY (TimelineItemId);

ALTER TABLE snprc_scheduler.TimelineItem
  ADD CONSTRAINT AK_TimelineItemObjectId UNIQUE (ObjectId);


/*==============================================================*/
/* Index: IDXC_TimelineItemFK2                                  */
/*==============================================================*/
CREATE INDEX IDXC_TimelineItemFK2 ON snprc_scheduler.TimelineItem (
  ProjectItemId ASC
);

/*==============================================================*/
/* Index: IDX_TimelineItemFK1                                   */
/*==============================================================*/
CREATE INDEX IDX_TimelineItemFK1 ON snprc_scheduler.TimelineItem (
  TimelineObjectId ASC
);

ALTER TABLE snprc_scheduler.Timelineitem
  ADD CONSTRAINT FK_TimelineItem_Timeline FOREIGN KEY (TimelineObjectId)
REFERENCES snprc_scheduler.Timeline (ObjectId);

ALTER TABLE snprc_scheduler.Timelineitem
  ADD CONSTRAINT FK_TimelineItem_SNDProjectItem FOREIGN KEY (ProjectItemId)
REFERENCES snd.ProjectItems (ProjectItemId);

-- %% 2222222222 %%  end timelineItem

/*==============================================================*/
/* Table: Schedule  3                                            */
/*==============================================================*/
CREATE TABLE snprc_scheduler.Schedule (
  ScheduleId           integer GENERATED BY DEFAULT AS IDENTITY,
  TimelineItemId       int                  not null,
  TargetDate           timestamp            not null,
  Created              timestamp            null,
  CreatedBy            int                  null,
  Modified             timestamp            null,
  ModifiedBy           int                  null,
  ObjectId             ENTITYID             not null
);

ALTER TABLE snprc_scheduler.Schedule
  ADD CONSTRAINT PK_Schedule PRIMARY KEY (ScheduleId);


/*==============================================================*/
/* Index: IDX_ScheduleFK1                                       */
/*==============================================================*/
CREATE INDEX IDX_ScheduleFK1 ON snprc_scheduler.Schedule (
  TimelineItemId ASC
);


ALTER TABLE snprc_scheduler.Schedule
  ADD CONSTRAINT FK_ScheduleFK1 FOREIGN KEY (TimelineItemId)
REFERENCES snprc_scheduler.TimelineItem (TimelineItemId);


-- %%% 333333 %%%  end Schedule

/*==============================================================*/
/* Table: TimelineProjectItem   4                                   */
/*==============================================================*/
CREATE TABLE snprc_scheduler.TimelineProjectItem (
  ProjectItemId        int                  not null,
  TimelineObjectId     ENTITYID             not null,
  TimelineId           int                  not null,
  TimelineRevisionNum  int                  not null,
  TimelineFootNotes    varchar(100)         null,
  SortOrder            int                  not null
);

ALTER TABLE snprc_scheduler.TimelineProjectItem
  ADD CONSTRAINT PK_TimelineProjectItem PRIMARY KEY (TimelineObjectId, ProjectItemId);

/*==============================================================*/
/* Index: IDX_TimelineProjectItemFK1                            */
/*==============================================================*/
CREATE INDEX IDX_TimelineProjectItemFK1 ON snprc_scheduler.TimelineProjectItem (
  TimelineObjectid ASC
);

/*==============================================================*/
/* Index: IDX_TimelineItemFK2                                   */
/*==============================================================*/
CREATE INDEX IDX_TimelineProjectItemFK2 ON snprc_scheduler.TimelineProjectItem (
  ProjectItemId ASC
);

ALTER TABLE snprc_scheduler.TimelineProjectItem
  ADD CONSTRAINT FK_TimelineProjectItem_SndProject FOREIGN KEY (ProjectItemId)
REFERENCES snd.ProjectItems (ProjectitemId);

ALTER TABLE snprc_scheduler.TimelineProjectItem
  ADD CONSTRAINT FK_TimelineProjectItem FOREIGN KEY (TimelineObjectId)
REFERENCES snprc_scheduler.Timeline (ObjectId);



-- %%%%%%%   4444444 %%%%%%%%%%%% end TimelineProjectItem

/*==============================================================*/
/* Table: timelineanimaljunction  5                              */
/*==============================================================*/
CREATE TABLE snprc_scheduler.TimelineAnimalJunction (
  RowId                integer GENERATED BY DEFAULT AS IDENTITY,
  AnimalId             varchar(50)          not null,
  TimelineObjectId     ENTITYID             null,
  StartDate            date                 null,
  StopDate             date                 null,
  Created              timestamp            null,
  CreatedBy            int                  null,
  Modified             timestamp            null,
  ModifiedBy           int                  null,
  ObjectId             ENTITYID             not null
);

ALTER TABLE snprc_scheduler.TimelineAnimalJunction
  ADD CONSTRAINT PK_TimelineAnimalJunction PRIMARY KEY (RowId);


/*==============================================================*/
/* Index: IDXC_TimelineAnimalJunctionFK1                        */
/*==============================================================*/
CREATE INDEX IDXC_TimelineAnimalJunctionFK1 ON snprc_scheduler.TimelineAnimalJunction (
  TimelineObjectId ASC
);

/*==============================================================*/
/* Index: IDX_TimelineAnimalJunctionFK2                         */
/*==============================================================*/
CREATE INDEX IDX_TimelineAnimalJunctionFK2 ON snprc_scheduler.TimelineAnimalJunction (
  AnimalID ASC
);


ALTER TABLE snprc_scheduler.TimelineAnimalJunction
  ADD CONSTRAINT FK_TimelineJunction_Timeline FOREIGN KEY (TimelineObjectId)
REFERENCES snprc_scheduler.Timeline (ObjectId);

/******************************************************

   rename snprc_scheduler.TimelineAnimalJunction.StopDate to EndDate

srr 11.12.2018
******************************************************/

ALTER TABLE snprc_scheduler.TimelineAnimalJunction RENAME COLUMN StopDate TO Tmp_EndDate;
ALTER TABLE snprc_scheduler.TimelineAnimalJunction RENAME COLUMN Tmp_EndDate TO EndDate;

ALTER TABLE snprc_scheduler.TimelineAnimalJunction
  DROP COLUMN StartDate;
--  END   rename StopDate  to EndDate



/*#######################################################################
Change column:
 ScheduleDay int
to
 ScheduleDate date





srr. 11.12.18
#######################################################################    */



ALTER TABLE snprc_scheduler.TimelineItem DROP CONSTRAINT FK_TimelineItem_Timeline;

ALTER TABLE snprc_scheduler.TimelineItem DROP CONSTRAINT FK_TimelineItem_SNDProjectItem;

ALTER TABLE snprc_scheduler.Schedule DROP CONSTRAINT FK_ScheduleFK1;


/****** Object:  Table [snprc_scheduler].[TimelineItem]    Script Date: 11/12/2018 11:42:24 AM ******/
DROP TABLE snprc_scheduler.TimelineItem;




/**/
/*==============================================================*/
/* Table: TimelineItem       2                                   */
/*==============================================================*/
CREATE TABLE snprc_scheduler.TimelineItem (
  TimelineItemId       integer GENERATED BY DEFAULT AS IDENTITY,
  ProjectitemId        int                  not null,
  TimelineObjectId     ENTITYID             not null,
  StudyDay             int                  null,
  ScheduleDate         timestamp            null,
  Created              timestamp            null,
  CreatedBy            int                  null,
  Modified             timestamp            null,
  ModifiedBy           int                  null,
  ObjectId             ENTITYID             not null
);

ALTER TABLE snprc_scheduler.TimelineItem
  ADD CONSTRAINT PK_TimelineItem PRIMARY KEY (TimelineItemId);

ALTER TABLE snprc_scheduler.TimelineItem
  ADD CONSTRAINT AK_TimelineItemObjectId UNIQUE (ObjectId);


/*==============================================================*/
/* Index: IDXC_TimelineItemFK2                                  */
/*==============================================================*/
CREATE INDEX IDXC_TimelineItemFK2 ON snprc_scheduler.TimelineItem (
ProjectItemId ASC
);

/*==============================================================*/
/* Index: IDX_TimelineItemFK1                                   */
/*==============================================================*/
CREATE INDEX IDX_TimelineItemFK1 ON snprc_scheduler.TimelineItem (
  TimelineObjectId ASC
);

ALTER TABLE snprc_scheduler.Timelineitem
  ADD CONSTRAINT FK_TimelineItem_Timeline FOREIGN KEY (TimelineObjectId)
REFERENCES snprc_scheduler.Timeline (ObjectId);

ALTER TABLE snprc_scheduler.Timelineitem
  ADD CONSTRAINT FK_TimelineItem_SNDProjectItem FOREIGN KEY (ProjectItemId)
REFERENCES snd.ProjectItems (ProjectItemId);

ALTER TABLE snprc_scheduler.Schedule
  ADD CONSTRAINT FK_ScheduleFK1 FOREIGN KEY (TimelineItemId)
REFERENCES snprc_scheduler.TimelineItem (TimelineItemId);

/***********************************************
Adding Created,Modified and ObjectId

Populate ObjectId for current data,
set to NOT NULL


srr 11.28.2018
srr 12.05.2018  Removed SETs
***********************************************/

BEGIN;

ALTER TABLE snprc_scheduler.TimelineProjectItem 
  ADD COLUMN Created timestamp NULL,
  ADD COLUMN CreatedBy int NULL,
  ADD COLUMN Modified timestamp NULL,
  ADD COLUMN ModifiedBy int NULL,
  ADD COLUMN ObjectId ENTITYID NULL;

ALTER TABLE snprc_scheduler.TimelineProjectItem
  DROP COLUMN TimelineId, 
  DROP COLUMN TimelineRevisionNum;

ALTER TABLE snprc_scheduler.TimelineProjectItem
  ALTER COLUMN ObjectId SET NOT NULL;

COMMIT;

/***********************************************
Table snprc_Scheduler.Schedule was refactored out
Dropping the table and FK


srr 11.30.2018
***********************************************/
ALTER TABLE snprc_scheduler.Schedule DROP CONSTRAINT IF EXISTS FK_ScheduleFK1;

DROP TABLE IF EXISTS snprc_scheduler.Schedule;

/*******************************************
TimelineObjectId should be NOT NULL
srr 12.04.2018
*******************************************/
DROP INDEX IF EXISTS snprc_scheduler.IDXC_TimelineAnimalJunctionFK1;

-- set TimelineObjectId to NOT NULL
ALTER TABLE snprc_scheduler.TimelineAnimalJunction
  ALTER COLUMN TimelineObjectId SET NOT NULL;


CREATE INDEX IDXC_TimelineAnimalJunctionFK1 ON snprc_scheduler.TimelineAnimalJunction
(
TimelineObjectId ASC
);

/*******************************************
Add RC to Timeline table
srr 01.08.2019
*******************************************/
ALTER TABLE snprc_scheduler.Timeline ADD COLUMN RC varchar(50) NULL;

/*******************************************
Add AnimalAccount to Timeline table
Will hold a concated list of animal acccount
for this project.
NOTE: Reference only, not validated
srr 05.22.2019
*******************************************/
ALTER TABLE snprc_scheduler.Timeline
    ADD COLUMN AnimalAccount varchar(255) NULL;

-- drop table if it exists
SELECT core.fn_dropifexists('StudyDayNotes','snprc_scheduler', 'TABLE');


/********************************************
Create table to hold day specific study notes.

C:\MySoftware\labkey\trunk\externalModules\snprcEHRModules
snprcEHRModules
srr 05.22.2019
*********************************************/
/*==============================================================*/
/* Table: StudyDayNotes                                         */
/*==============================================================*/
CREATE TABLE snprc_scheduler.StudyDayNotes
(
    ObjectId ENTITYID NOT NULL,
    TimelineObjectId UNIQUEIDENTIFIER NULL,
    StudyDay INT NULL,
    StudyDayNote TEXT NULL,
    QcState INT NULL,
    Created TIMESTAMP NULL,
    CreatedBy INT NULL,
    Modified TIMESTAMP NULL,
    ModifiedBy INT NULL
);

ALTER TABLE snprc_scheduler.StudyDayNotes
    ADD CONSTRAINT PK_STUDYDAYNOTES
        PRIMARY KEY (ObjectId);


/***************************************
Integrity triggers


  srr 05.28.2019
 **************************************/

/*****************************  snprc_scheduler.tia_StudyDayNotes  *****************************************/

/*	For referential integrity only.
	Sole purpose is to prevent a note entry for (timeline-study day) that does not exists.
	For INSERT and UPDATE
 */
CREATE OR REPLACE FUNCTION snprc_scheduler.tiu_StudyDayNotes_fn()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM snprc_scheduler.TimelineItem t
        WHERE t.StudyDay = NEW.StudyDay
          AND t.TimelineObjectId = NEW.TimelineObjectId
    ) THEN
        RAISE EXCEPTION 'StudyDayNotes Trigger - TimelineObjectId - StudyDay pair do not exist SNPRC_Scheduler.Timelineitem. Cannot insert to SNPRC_Scheduler.StudyDayNotes';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tiu_StudyDayNotes
    BEFORE INSERT OR UPDATE
    ON snprc_scheduler.StudyDayNotes
    FOR EACH ROW
    EXECUTE FUNCTION snprc_scheduler.tiu_StudyDayNotes_fn();

ALTER TABLE snprc_scheduler.StudyDayNotes ENABLE TRIGGER tiu_StudyDayNotes;

/*****************************  snprc_scheduler.td_TimelineItem  *****************************************/

CREATE OR REPLACE FUNCTION snprc_scheduler.td_TimelineItem_fn()
RETURNS TRIGGER AS $$
BEGIN
    /*****************************************************
     StudyDayNotes was an late addition to model.
    This trigger’s sole purpose is to enforce referential integrity
      between TimelineItem and StudyDayNotes tables
    Each study day note requires one or more rows in the TimelineItem table.
    srr 06.07.19
     ****************************************************/
    IF EXISTS (
        SELECT 1
        FROM snprc_scheduler.StudyDayNotes n
        WHERE n.StudyDay = OLD.StudyDay AND n.TimelineObjectId = OLD.TimelineObjectId
    ) AND NOT EXISTS (
        SELECT 1
        FROM snprc_scheduler.TimelineItem t
        WHERE t.StudyDay = OLD.StudyDay AND t.TimelineObjectId = OLD.TimelineObjectId
    ) THEN
        RAISE EXCEPTION 'Timeline Item Trigger - TimelineItem has a StudyDayNote and only item on Study day.  Note must be deleted first.  Data not modified.';
    END IF;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER td_TimelineItem
    AFTER DELETE
    ON snprc_scheduler.TimelineItem
    FOR EACH ROW
    EXECUTE FUNCTION snprc_scheduler.td_TimelineItem_fn();

ALTER TABLE snprc_scheduler.TimelineItem ENABLE TRIGGER td_TimelineItem;

/******************************************/
-- setting ProjectItemID to NOT NULL


ALTER TABLE snprc_scheduler.TimelineItem
    ALTER COLUMN ProjectitemId DROP NOT NULL;

--srr 05.29.19
/*****************************************/

/******************************
Added unique index to FK columns
  to ensure no duplicate rows.

srr 06.10.2019
******************************/

CREATE UNIQUE INDEX idx_u_FK_to_TimelineItem ON snprc_scheduler.StudyDayNotes
(
	TimelineObjectId ASC,
	StudyDay ASC
);

ALTER TABLE snprc_scheduler.StudyDayNotes
    DROP COLUMN QcState;
