CREATE SCHEMA snprc_scheduler;

/*==============================================================*/
/* Table: Timeline                                              */
/*==============================================================*/
CREATE TABLE snprc_scheduler.Timeline (
  TimelineId           int                  not null,
  RevisionNum          int                  not null,
  ProjectObjectId      ENTITYID             not null,
  StartDate            date                 null,
  EndDate              date                 null,
  Description          varchar(255)         null,
  LeadTech             varchar(50)          null,
  Notes                text                 null,
  SchedulerNotes       varchar(500)         null,
  QcState              int                  null,
  Created              timestamp            null,
  CreatedBy            int                  null,
  Modified             timestamp            null,
  ModifiedBy           int                  null,
  ObjectId             ENTITYID             not null,
  RC                   varchar(50)          null,
  AnimalAccount        varchar(255)         null,
  CONSTRAINT PK_Timeline PRIMARY KEY (TimelineId, RevisionNum),
  CONSTRAINT AK_TimelineObjectId UNIQUE (ObjectId),
  CONSTRAINT FK_Timeline_SNDProject FOREIGN KEY (ProjectObjectId) REFERENCES snd.projects (Objectid)
);

COMMENT ON TABLE snprc_scheduler.Timeline IS 'Data Dict';
COMMENT ON COLUMN snprc_scheduler.Timeline.Notes IS 'Added during 9/17/18 meeting. Size TBD';
COMMENT ON COLUMN snprc_scheduler.Timeline.QcState IS 'Will handle isActive function';

CREATE INDEX IDX_TimelineFK1 ON snprc_scheduler.Timeline (
  ProjectObjectId ASC
);


/*==============================================================*/
/* Table: TimelineItem                                          */
/*==============================================================*/
CREATE TABLE snprc_scheduler.TimelineItem (
  TimelineItemId       integer GENERATED BY DEFAULT AS IDENTITY,
  ProjectitemId        int                  null,
  TimelineObjectId     ENTITYID             not null,
  StudyDay             int                  null,
  ScheduleDate         timestamp            null,
  Created              timestamp            null,
  CreatedBy            int                  null,
  Modified             timestamp            null,
  ModifiedBy           int                  null,
  ObjectId             ENTITYID             not null,
  CONSTRAINT PK_TimelineItem PRIMARY KEY (TimelineItemId),
  CONSTRAINT AK_TimelineItemObjectId UNIQUE (ObjectId),
  CONSTRAINT FK_TimelineItem_Timeline FOREIGN KEY (TimelineObjectId) REFERENCES snprc_scheduler.Timeline (ObjectId),
  CONSTRAINT FK_TimelineItem_SNDProjectItem FOREIGN KEY (ProjectItemId) REFERENCES snd.ProjectItems (ProjectItemId)
);

CREATE INDEX IDXC_TimelineItemFK2 ON snprc_scheduler.TimelineItem (
  ProjectItemId ASC
);

CREATE INDEX IDX_TimelineItemFK1 ON snprc_scheduler.TimelineItem (
  TimelineObjectId ASC
);


/*==============================================================*/
/* Table: TimelineProjectItem                                   */
/*==============================================================*/
CREATE TABLE snprc_scheduler.TimelineProjectItem (
  ProjectItemId        int                  not null,
  TimelineObjectId     ENTITYID             not null,
  TimelineFootNotes    varchar(100)         null,
  SortOrder            int                  not null,
  Created              timestamp            null,
  CreatedBy            int                  null,
  Modified             timestamp            null,
  ModifiedBy           int                  null,
  ObjectId             ENTITYID             not null,
  CONSTRAINT PK_TimelineProjectItem PRIMARY KEY (TimelineObjectId, ProjectItemId),
  CONSTRAINT FK_TimelineProjectItem_SndProject FOREIGN KEY (ProjectItemId) REFERENCES snd.ProjectItems (ProjectitemId),
  CONSTRAINT FK_TimelineProjectItem FOREIGN KEY (TimelineObjectId) REFERENCES snprc_scheduler.Timeline (ObjectId)
);

CREATE INDEX IDX_TimelineProjectItemFK1 ON snprc_scheduler.TimelineProjectItem (
  TimelineObjectId ASC
);

CREATE INDEX IDX_TimelineProjectItemFK2 ON snprc_scheduler.TimelineProjectItem (
  ProjectItemId ASC
);


/*==============================================================*/
/* Table: TimelineAnimalJunction                                */
/*==============================================================*/
CREATE TABLE snprc_scheduler.TimelineAnimalJunction (
  RowId                integer GENERATED BY DEFAULT AS IDENTITY,
  AnimalId             varchar(50)          not null,
  TimelineObjectId     ENTITYID             not null,
  EndDate              date                 null,
  Created              timestamp            null,
  CreatedBy            int                  null,
  Modified             timestamp            null,
  ModifiedBy           int                  null,
  ObjectId             ENTITYID             not null,
  CONSTRAINT PK_TimelineAnimalJunction PRIMARY KEY (RowId),
  CONSTRAINT FK_TimelineJunction_Timeline FOREIGN KEY (TimelineObjectId) REFERENCES snprc_scheduler.Timeline (ObjectId)
);

CREATE INDEX IDXC_TimelineAnimalJunctionFK1 ON snprc_scheduler.TimelineAnimalJunction (
  TimelineObjectId ASC
);

CREATE INDEX IDX_TimelineAnimalJunctionFK2 ON snprc_scheduler.TimelineAnimalJunction (
  AnimalId ASC
);


/*==============================================================*/
/* Table: StudyDayNotes                                         */
/*==============================================================*/
CREATE TABLE snprc_scheduler.StudyDayNotes (
  ObjectId             ENTITYID             not null,
  TimelineObjectId     UNIQUEIDENTIFIER     null,
  StudyDay             int                  null,
  StudyDayNote         text                 null,
  Created              timestamp            null,
  CreatedBy            int                  null,
  Modified             timestamp            null,
  ModifiedBy           int                  null,
  CONSTRAINT PK_StudyDayNotes PRIMARY KEY (ObjectId)
);

-- NULLS NOT DISTINCT (PostgreSQL 15+) so two rows with a NULL StudyDay still collide.
CREATE UNIQUE INDEX idx_u_FK_to_TimelineItem ON snprc_scheduler.StudyDayNotes (
  TimelineObjectId ASC,
  StudyDay ASC
) NULLS NOT DISTINCT;


/*==============================================================*/
/* Triggers & Integrity Functions                               */
/*==============================================================*/

-- Trigger Function: tiu_StudyDayNotes_fn
CREATE OR REPLACE FUNCTION snprc_scheduler.tiu_StudyDayNotes_fn()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM snprc_scheduler.TimelineItem t
        WHERE t.StudyDay = NEW.StudyDay
          AND t.TimelineObjectId = NEW.TimelineObjectId
    ) THEN
        RAISE EXCEPTION 'StudyDayNotes Trigger - TimelineObjectId - StudyDay pair do not exist SNPRC_Scheduler.Timelineitem. Cannot insert to SNPRC_Scheduler.StudyDayNotes';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: tiu_StudyDayNotes
CREATE TRIGGER tiu_StudyDayNotes
    BEFORE INSERT OR UPDATE
    ON snprc_scheduler.StudyDayNotes
    FOR EACH ROW
    EXECUTE FUNCTION snprc_scheduler.tiu_StudyDayNotes_fn();

ALTER TABLE snprc_scheduler.StudyDayNotes ENABLE TRIGGER tiu_StudyDayNotes;


-- Trigger Function: td_TimelineItem_fn
CREATE OR REPLACE FUNCTION snprc_scheduler.td_TimelineItem_fn()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM snprc_scheduler.StudyDayNotes n
        WHERE n.StudyDay = OLD.StudyDay AND n.TimelineObjectId = OLD.TimelineObjectId
    ) AND NOT EXISTS (
        SELECT 1
        FROM snprc_scheduler.TimelineItem t
        WHERE t.StudyDay = OLD.StudyDay AND t.TimelineObjectId = OLD.TimelineObjectId
    ) THEN
        RAISE EXCEPTION 'Timeline Item Trigger - TimelineItem has a StudyDayNote and only item on Study day.  Note must be deleted first.  Data not modified.';
    END IF;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- Trigger: td_TimelineItem
CREATE TRIGGER td_TimelineItem
    AFTER DELETE
    ON snprc_scheduler.TimelineItem
    FOR EACH ROW
    EXECUTE FUNCTION snprc_scheduler.td_TimelineItem_fn();

ALTER TABLE snprc_scheduler.TimelineItem ENABLE TRIGGER td_TimelineItem;
