/*
 * Copyright (c) 2016-2026 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.labkey.gradle.util.GroupNames
import org.labkey.gradle.util.BuildUtils

sourceSets {
    transform {
        java {
            srcDirs = ['resources/transform/src']
        }
    }
}

dependencies {
    transformImplementation "org.apache.poi:poi:${poiVersion}"
    transformImplementation "org.apache.poi:poi-ooxml:${poiVersion}"
    transformImplementation "org.apache.pdfbox:pdfbox:${pdfboxVersion}"
    transformImplementation "com.google.guava:guava:${guavaVersion}"
    transformImplementation "org.apache.commons:commons-collections4:${commonsCollections4Version}"
}

configurations {
    transformJars {
        canBeResolved = true
        extendsFrom(transformImplementation)
    }
}

project.tasks.register("transformJar", Jar)
        {Jar jar ->
            jar.group = GroupNames.BUILD
            jar.description = "Create the transform jar file"

            jar.from project.sourceSets.transform.output
            jar.from { configurations.transformJars.collect { it.isDirectory() ? it : zipTree(it) }}
            jar.archiveBaseName.set("MicrobiomeTransform")
            jar.archiveClassifier.set("transform")
            jar.duplicatesStrategy = DuplicatesStrategy.EXCLUDE
            jar.destinationDirectory.set(BuildUtils.getBuildDirFile(project, "artifacts/snprc"))
            jar.manifest {
                attributes "Main-Class": "MicrobiomeTransform"
            }
        }

project.tasks.assemble.dependsOn(project.tasks.transformJar)

project.tasks.named('module').configure { dependsOn(project.tasks.transformJar) }
