/*******************************************************
New staging tables for Orchard clinical path data integration via HL7
05/19/22 - Terry Hawkins
*/

/*
 Drop tables if they already exist
*/

EXEC core.fn_dropifexists @objname = 'HL7_IMPORT_LOG',@objschema = 'snprc_ehr', @objtype = 'TABLE';
EXEC core.fn_dropifexists @objname = 'HL7_OBX_Staging',@objschema = 'snprc_ehr', @objtype = 'TABLE';
EXEC core.fn_dropifexists @objname = 'HL7_NTE_Staging',@objschema = 'snprc_ehr', @objtype = 'TABLE';
EXEC core.fn_dropifexists @objname = 'HL7_OBR_Staging',@objschema = 'snprc_ehr', @objtype = 'TABLE';
EXEC core.fn_dropifexists @objname = 'HL7_PID_Staging',@objschema = 'snprc_ehr', @objtype = 'TABLE';
EXEC core.fn_dropifexists @objname = 'HL7_PV1_Staging',@objschema = 'snprc_ehr', @objtype = 'TABLE';
EXEC core.fn_dropifexists @objname = 'HL7_ORC_Staging',@objschema = 'snprc_ehr', @objtype = 'TABLE';
EXEC core.fn_dropifexists @objname = 'HL7_MSH_Staging',@objschema = 'snprc_ehr', @objtype = 'TABLE';

CREATE TABLE [snprc_ehr].[HL7_MSH_Staging](
    [MESSAGE_ID] [VARCHAR](50) NOT NULL,
    [IDX] [INT] NOT NULL,
    [SENDING_APPLICATION] [VARCHAR](50) NULL,
    [SENDING_FACILITY] [VARCHAR](50) NULL,
    [RECEIVING_APPLICATION] [VARCHAR](50) NULL,
    [RECEIVING_FACILITY] [VARCHAR](50) NULL,
    [MESSAGE_CONTROL_ID] [VARCHAR](50) NULL,
    [MESSAGE_DATE_TM] [DATETIME] NULL,
    [OBJECT_ID] [UNIQUEIDENTIFIER] NOT NULL,
    [USER_NAME] [VARCHAR](128) NOT NULL,
    [ENTRY_DATE_TM] [DATETIME] NOT NULL,
    [TIMESTAMP] [TIMESTAMP] NULL,
    CONSTRAINT [PK_HL7_MSH_Staging] PRIMARY KEY CLUSTERED
(
    [MESSAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
    )
    GO

ALTER TABLE [snprc_ehr].[HL7_MSH_Staging] ADD  CONSTRAINT [DF_HL7_MSH_Staging_OBJECT_ID]  DEFAULT (NEWID()) FOR [OBJECT_ID]
    GO

ALTER TABLE [snprc_ehr].[HL7_MSH_Staging] ADD  CONSTRAINT [DF_HL7_MSH_Staging_USER]  DEFAULT (USER_NAME()) FOR [USER_NAME]
    GO

ALTER TABLE [snprc_ehr].[HL7_MSH_Staging] ADD  CONSTRAINT [DF_HL7_MSH_Staging_ENTRY]  DEFAULT (GETDATE()) FOR [ENTRY_DATE_TM]
    GO

CREATE TABLE [snprc_ehr].[HL7_PID_Staging](
    [MESSAGE_ID] [VARCHAR](50) NOT NULL,
    [IDX] [INT] NOT NULL,
    [SET_ID] [VARCHAR](20) NULL, -- F1_C1
    [PATIENT_ID_EXTERNAL] [VARCHAR](20) NULL, -- F2_C1
    [PATIENT_ID_INTERNAL] [VARCHAR](20) NULL, -- F3_C1
    [BIRTHDATE] [DATETIME] NULL, --F7_C1
    [SEX] [VARCHAR] (20) NULL, -- F8_C1
    [BREED] [VARCHAR] (50) NULL,  -- arc_species_code - F10_C1 (Race)
    [SPECIES] [VARCHAR] (50) NULL, -- common name - F22_C1 (Ethnic Group)
    [ACCOUNT_NUMBER] [VARCHAR] (50) NULL, --F18_C1
    [DEATH_DATE] [VARCHAR] (50) NULL, -- F29_C1
    [OBJECT_ID] [UNIQUEIDENTIFIER] NOT NULL,
    [USER_NAME] [VARCHAR](128) NOT NULL,
    [ENTRY_DATE_TM] [DATETIME] NOT NULL,
    [TIMESTAMP] [TIMESTAMP] NULL,
    CONSTRAINT [PK_HL7_PID_Staging] PRIMARY KEY CLUSTERED
(
[MESSAGE_ID] ASC,
[IDX]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
    )
    GO

ALTER TABLE [snprc_ehr].[HL7_PID_Staging] ADD  CONSTRAINT [DF_HL7_PID_Staging_OBJECT_ID]  DEFAULT (NEWID()) FOR [OBJECT_ID]
    GO

ALTER TABLE [snprc_ehr].[HL7_PID_Staging] ADD  CONSTRAINT [DF_HL7_PID_Staging_USER]  DEFAULT (USER_NAME()) FOR [USER_NAME]
    GO

ALTER TABLE [snprc_ehr].[HL7_PID_Staging] ADD  CONSTRAINT [DF_HL7_PID_Staging_ENTRY]  DEFAULT (GETDATE()) FOR [ENTRY_DATE_TM]
    GO

ALTER TABLE [snprc_ehr].[HL7_PID_Staging]  WITH CHECK ADD  CONSTRAINT [FK_PID_REF_MSH] FOREIGN KEY([MESSAGE_ID])
    REFERENCES [snprc_ehr].[HL7_MSH_Staging] ([MESSAGE_ID])
    GO

CREATE NONCLUSTERED INDEX [IDX_HL7_PID_ID] ON [snprc_ehr].[HL7_PID_Staging]
(
	[PATIENT_ID_EXTERNAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


ALTER TABLE [snprc_ehr].[HL7_PID_Staging] CHECK CONSTRAINT [FK_PID_REF_MSH]
    GO

CREATE TABLE [snprc_ehr].[HL7_PV1_Staging](
    [MESSAGE_ID] [VARCHAR](50) NOT NULL,
    [IDX] [INT] NOT NULL,
    [SET_ID] [VARCHAR](20) NULL, -- F1_C1
    [ADMISSION_TYPE] [VARCHAR] (20) NULL, --F4_C1
    [ATTENDING_DOCTOR_LAST] [VARCHAR] (50) NULL, -- F7_C2
    [ATTENDING_DOCTOR_FIRST] [VARCHAR] (50) NULL, -- F7_C3
    [VISIT_NUMBER] [VARCHAR] (20) NULL, -- F19_C1
    [CHARGE_NUMBER] [VARCHAR] (20) NULL, -- F22_C1 (Courtesy Code)
    [ADMIT_DATE] [DATETIME] NULL, --F44_C1
    [OBJECT_ID] [UNIQUEIDENTIFIER] NOT NULL,
    [USER_NAME] [VARCHAR](128) NOT NULL,
    [ENTRY_DATE_TM] [DATETIME] NOT NULL,
    [TIMESTAMP] [TIMESTAMP] NULL,
    CONSTRAINT [PK_HL7_PV1_Staging] PRIMARY KEY CLUSTERED
(
    [MESSAGE_ID] ASC,
[IDX]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
    )
    GO

ALTER TABLE [snprc_ehr].[HL7_PV1_Staging] ADD  CONSTRAINT [DF_HL7_PV1_Staging_OBJECT_ID]  DEFAULT (NEWID()) FOR [OBJECT_ID]
    GO

ALTER TABLE [snprc_ehr].[HL7_PV1_Staging] ADD  CONSTRAINT [DF_HL7_PV1_Staging_USER]  DEFAULT (USER_NAME()) FOR [USER_NAME]
    GO

ALTER TABLE [snprc_ehr].[HL7_PV1_Staging] ADD  CONSTRAINT [DF_HL7_PV1_Staging_ENTRY]  DEFAULT (GETDATE()) FOR [ENTRY_DATE_TM]
    GO

ALTER TABLE [snprc_ehr].[HL7_PV1_Staging]  WITH CHECK ADD  CONSTRAINT [FK_PV1_REF_MSH] FOREIGN KEY([MESSAGE_ID])
    REFERENCES [snprc_ehr].[HL7_MSH_Staging] ([MESSAGE_ID])
    GO

ALTER TABLE [snprc_ehr].[HL7_PV1_Staging] CHECK CONSTRAINT [FK_PV1_REF_MSH]
    GO

CREATE TABLE [snprc_ehr].[HL7_ORC_Staging](
    [MESSAGE_ID] [VARCHAR](50) NOT NULL,
    [IDX] [INT] NOT NULL,
    [ORDER_CONTROL_CODE] [VARCHAR](20) NULL, -- F1_C1
    [FILLER_ORDER_NUMBER] [VARCHAR] (22) NULL, --F3_C1
    [ENTERED_BY_LAST] [VARCHAR] (50) NULL, -- F10_C2
    [ENTERED_BY_FIRST] [VARCHAR] (50) NULL, -- F10_C3
    [VERIFIED_BY_LAST] [VARCHAR] (50) NULL, -- F11_C2
    [VERIFIED_BY_FIRST] [VARCHAR] (50) NULL, -- F11_C3
    [ORDER_PROVIDER_LAST] [VARCHAR] (50) NULL, -- F12_C2
    [ORDER_PROVIDER_FIRST] [VARCHAR] (50) NULL, -- F12_C3
    [ORDER_DATE] [DATETIME] NULL, -- F15_C1
    [OBJECT_ID] [UNIQUEIDENTIFIER] NOT NULL,
    [USER_NAME] [VARCHAR](128) NOT NULL,
    [ENTRY_DATE_TM] [DATETIME] NOT NULL,
    [TIMESTAMP] [TIMESTAMP] NULL,
    CONSTRAINT [PK_HL7_ORC_Staging] PRIMARY KEY CLUSTERED
(
    [MESSAGE_ID] ASC,
[IDX]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
    )
    GO

ALTER TABLE [snprc_ehr].[HL7_ORC_Staging] ADD  CONSTRAINT [DF_HL7_ORC_Staging_OBJECT_ID]  DEFAULT (NEWID()) FOR [OBJECT_ID]
    GO

ALTER TABLE [snprc_ehr].[HL7_ORC_Staging] ADD  CONSTRAINT [DF_HL7_ORC_Staging_USER]  DEFAULT (USER_NAME()) FOR [USER_NAME]
    GO

ALTER TABLE [snprc_ehr].[HL7_ORC_Staging] ADD  CONSTRAINT [DF_HL7_ORC_Staging_ENTRY]  DEFAULT (GETDATE()) FOR [ENTRY_DATE_TM]
    GO

ALTER TABLE [snprc_ehr].[HL7_ORC_Staging]  WITH CHECK ADD  CONSTRAINT [FK_ORC_REF_MSH] FOREIGN KEY([MESSAGE_ID])
    REFERENCES [snprc_ehr].[HL7_MSH_Staging] ([MESSAGE_ID])
    GO

ALTER TABLE [snprc_ehr].[HL7_ORC_Staging] CHECK CONSTRAINT [FK_ORC_REF_MSH]
    GO


CREATE TABLE [snprc_ehr].[HL7_OBR_Staging](
    [MESSAGE_ID] [VARCHAR](50) NOT NULL,
    [MESSAGE_CONTROL_ID] [VARCHAR](50) NOT NULL,
    [IDX] [INT] NOT NULL,
    [ANIMAL_ID] [VARCHAR](6) NOT NULL,
    [VERIFIED_DATE_TM] [DATETIME] NULL,
    [REQUESTED_DATE_TM] [DATETIME] NULL,
    [OBSERVATION_DATE_TM] [DATETIME] NULL,
    [SPECIMEN_RECEIVED_DATE_TM] [DATETIME] NULL,
    [PV1_VISIT_NUM] [VARCHAR](50) NULL,
    [SET_ID] [VARCHAR](20) NOT NULL,
    [SPECIMEN_NUM] [VARCHAR](50) NULL,
    [PROCEDURE_ID] [VARCHAR](20) NULL,
    [PROCEDURE_NAME] [VARCHAR](20) NULL,
    [PRIORITY] [VARCHAR](10) NULL,
    [RESULT_STATUS] [VARCHAR](10) NULL,
    [TECHNICIAN_NAME] [VARCHAR](MAX) NULL,
    [TECHNICIAN_INITIALS] [VARCHAR](50) NULL,
    [CHARGE_ID] [INT] NULL,
    [OBJECT_ID] [UNIQUEIDENTIFIER] NOT NULL,
    [USER_NAME] [VARCHAR](128) NOT NULL,
    [ENTRY_DATE_TM] [DATETIME] NOT NULL,
    [TIMESTAMP] [TIMESTAMP] NULL,
    CONSTRAINT [PK_HL7_OBR_Staging] PRIMARY KEY CLUSTERED
(
[OBJECT_ID]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

ALTER TABLE [snprc_ehr].[HL7_OBR_Staging] ADD  CONSTRAINT [DF_HL7_OBR_Staging_OBJECT_ID]  DEFAULT (NEWID()) FOR [OBJECT_ID]
    GO

ALTER TABLE [snprc_ehr].[HL7_OBR_Staging] ADD  CONSTRAINT [DF_HL7_OBR_Staging_USER]  DEFAULT (USER_NAME()) FOR [USER_NAME]
    GO

ALTER TABLE [snprc_ehr].[HL7_OBR_Staging] ADD  CONSTRAINT [DF_HL7_OBR_Staging_ENTRY]  DEFAULT (GETDATE()) FOR [ENTRY_DATE_TM]
    GO

ALTER TABLE [snprc_ehr].[HL7_OBR_Staging]  WITH CHECK ADD  CONSTRAINT [CKC_ENTRY_DATE_TM_HL7_OBR_Staging_OBR] CHECK  (([ENTRY_DATE_TM]<=GETDATE()))
    GO

ALTER TABLE [snprc_ehr].[HL7_OBR_Staging] CHECK CONSTRAINT [CKC_ENTRY_DATE_TM_HL7_OBR_Staging_OBR]
    GO

ALTER TABLE [snprc_ehr].[HL7_OBR_Staging]  WITH CHECK ADD  CONSTRAINT [FK_OBR_REF_MSH] FOREIGN KEY([MESSAGE_ID])
    REFERENCES [snprc_ehr].[HL7_MSH_Staging] ([MESSAGE_ID])
    GO

ALTER TABLE [snprc_ehr].[HL7_OBR_Staging] CHECK CONSTRAINT [FK_OBR_REF_MSH]
    GO

CREATE NONCLUSTERED INDEX [IDX_HL7_OBR_ID_DATE] ON [snprc_ehr].[HL7_OBR_Staging]
(
	[ANIMAL_ID] ASC,
	[OBSERVATION_DATE_TM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE TABLE [snprc_ehr].[HL7_OBX_Staging](
    [MESSAGE_ID] [VARCHAR](50) NOT NULL,
    [IDX] [INT] NOT NULL,
    [OBR_OBJECT_ID] [UNIQUEIDENTIFIER] NOT NULL,
    [SET_ID] [VARCHAR](20) NOT NULL,
    [OBR_SET_ID] [VARCHAR](20) NOT NULL,
    [VALUE_TYPE] [VARCHAR](10) NULL,
    [TEST_ID] [VARCHAR](20) NULL,
    [TEST_NAME] [VARCHAR](30) NULL,
    [OBSERVED_VALUE] [VARCHAR](MAX) NULL,
    [UNITS] [VARCHAR](20) NULL,
    [REFERENCE_RANGE] [VARCHAR](60) NULL,
    [ABNORMAL_FLAGS] [VARCHAR](10) NULL,
    [RESULT_STATUS] [VARCHAR](10) NULL,
    [OBJECT_ID] [UNIQUEIDENTIFIER] NOT NULL,
    [USER_NAME] [VARCHAR](128) NOT NULL,
    [ENTRY_DATE_TM] [DATETIME] NOT NULL,
    [TIMESTAMP] [TIMESTAMP] NULL,
    CONSTRAINT [PK_HL7_OBX_Staging] PRIMARY KEY CLUSTERED
(
    [OBJECT_ID]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

ALTER TABLE [snprc_ehr].[HL7_OBX_Staging] ADD  CONSTRAINT [DF_HL7_OBX_Staging_OBJECT_ID]  DEFAULT (NEWID()) FOR [OBJECT_ID]
    GO

ALTER TABLE [snprc_ehr].[HL7_OBX_Staging] ADD  CONSTRAINT [DF_HL7_OBX_Staging_USER]  DEFAULT (USER_NAME()) FOR [USER_NAME]
    GO

ALTER TABLE [snprc_ehr].[HL7_OBX_Staging] ADD  CONSTRAINT [DF_HL7_OBX_Staging_ENTRY]  DEFAULT (GETDATE()) FOR [ENTRY_DATE_TM]
    GO

ALTER TABLE [snprc_ehr].[HL7_OBX_Staging]  WITH CHECK ADD  CONSTRAINT [FK_OBX_REF_OBR] FOREIGN KEY([OBR_OBJECT_ID])
    REFERENCES [snprc_ehr].[HL7_OBR_Staging] ([OBJECT_ID])
    GO

ALTER TABLE [snprc_ehr].[HL7_OBX_Staging] CHECK CONSTRAINT [FK_OBX_REF_OBR]
    GO

CREATE NONCLUSTERED INDEX [IDX_HL7_OBX_OBR_OBJ_ID] ON [snprc_ehr].[HL7_OBX_Staging]
(
	[OBR_OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [snprc_ehr].[HL7_NTE_Staging](
    [MESSAGE_ID] [VARCHAR](50) NOT NULL,
    [IDX] [INT] NOT NULL,
    [OBR_OBJECT_ID] [UNIQUEIDENTIFIER] NOT NULL,
    [SET_ID] [VARCHAR](20) NOT NULL,
    [OBR_SET_ID] [VARCHAR](20) NOT NULL,
    [COMMENT] [VARCHAR](MAX) NULL,
    [OBJECT_ID] [UNIQUEIDENTIFIER] NOT NULL,
    [USER_NAME] [VARCHAR](128) NOT NULL,
    [ENTRY_DATE_TM] [DATETIME] NOT NULL,
    [TIMESTAMP] [TIMESTAMP] NULL,
    CONSTRAINT [PK_HL7_NTE_Staging] PRIMARY KEY CLUSTERED
(
    [OBJECT_ID] ASC

)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO

ALTER TABLE [snprc_ehr].[HL7_NTE_Staging] ADD  CONSTRAINT [DF_HL7_NTE_Staging_OBJECT_ID]  DEFAULT (NEWID()) FOR [OBJECT_ID]
    GO

ALTER TABLE [snprc_ehr].[HL7_NTE_Staging] ADD  CONSTRAINT [DF_HL7_NTE_Staging_USER]  DEFAULT (USER_NAME()) FOR [USER_NAME]
    GO

ALTER TABLE [snprc_ehr].[HL7_NTE_Staging] ADD  CONSTRAINT [DF_HL7_NTE_Staging_ENTRY]  DEFAULT (GETDATE()) FOR [ENTRY_DATE_TM]
    GO

ALTER TABLE [snprc_ehr].[HL7_NTE_Staging]  WITH CHECK ADD  CONSTRAINT [FK_NTE_REF_OBR] FOREIGN KEY([OBR_OBJECT_ID])
    REFERENCES [snprc_ehr].[HL7_OBR_Staging] ([OBJECT_ID])
    GO

ALTER TABLE [snprc_ehr].[HL7_NTE_Staging] CHECK CONSTRAINT [FK_NTE_REF_OBR]
    GO

CREATE NONCLUSTERED INDEX [IDX_HL7_NTE_OBR_OBJ_ID] ON [snprc_ehr].[HL7_NTE_Staging]
(
	[OBR_OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE TABLE [snprc_ehr].[HL7_IMPORT_LOG](
    [TID] [NUMERIC](18, 0) IDENTITY(1,1) NOT NULL,
    [MESSAGE_ID] [VARCHAR](50) NOT NULL,
    [OBSERVATION_DATE_TM] [DATETIME] NULL,
    [MESSAGE_CONTROL_ID] [VARCHAR](50) NULL,
    [IMPORT_STATUS] [INT] NOT NULL,
    [RESULT_STATUS] [VARCHAR](10) NULL,
    [PATIENT_ID] [VARCHAR](20) NULL,
    [SPECIES] [VARCHAR](50) NULL,
    [HL7_MESSAGE_TEXT] [VARCHAR](MAX) NULL,
    [IMPORT_TEXT] [VARCHAR](MAX) NULL,
    [OBJECT_ID] [UNIQUEIDENTIFIER] NOT NULL,
    [USER_NAME] [VARCHAR](128) NOT NULL,
    [ENTRY_DATE_TM] [DATETIME] NOT NULL,
    [TIMESTAMP] [TIMESTAMP] NULL,
    CONSTRAINT [PK_HL7_IMPORT_LOG] PRIMARY KEY CLUSTERED
(
[TID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
    )
    GO

ALTER TABLE [snprc_ehr].[HL7_IMPORT_LOG] ADD  DEFAULT (USER_NAME()) FOR [USER_NAME]
    GO

ALTER TABLE [snprc_ehr].[HL7_IMPORT_LOG] ADD  DEFAULT (GETDATE()) FOR [ENTRY_DATE_TM]
    GO

ALTER TABLE [snprc_ehr].[HL7_IMPORT_LOG] ADD  CONSTRAINT [DF_HL7_IMPROT_LOG_OBJECT_ID]  DEFAULT (NEWID()) FOR [OBJECT_ID]
    GO

ALTER TABLE [snprc_ehr].[HL7_IMPORT_LOG]  WITH CHECK ADD  CONSTRAINT [CKC_HL7_IMPORT_LOG_OBSERVATION_DATE] CHECK  (([OBSERVATION_DATE_TM] IS NULL OR [OBSERVATION_DATE_TM]<=GETDATE()))
    GO

ALTER TABLE [snprc_ehr].[HL7_IMPORT_LOG] CHECK CONSTRAINT [CKC_HL7_IMPORT_LOG_OBSERVATION_DATE]
    GO



