-- HL7_Admin permissions required for HL7 Schema Engine import
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON labkey.snprc_ehr.HL7_IMPORT_LOG TO HL7_Admin;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON labkey.snprc_ehr.HL7_MSH_Staging TO HL7_Admin;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON labkey.snprc_ehr.HL7_NTE_Staging TO HL7_Admin;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON labkey.snprc_ehr.HL7_OBR_Staging TO HL7_Admin;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON labkey.snprc_ehr.HL7_OBX_Staging TO HL7_Admin;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON labkey.snprc_ehr.HL7_ORC_Staging TO HL7_Admin;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON labkey.snprc_ehr.HL7_PID_Staging TO HL7_Admin;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON labkey.snprc_ehr.HL7_PV1_Staging TO HL7_Admin;