SELECT ls.LookupSetId,
       ls.SetName,
       ls.Label,
       ls.Description,
       ls.Container,
       ls.CreatedBy,
       ls.Created,
       ls.CreatedBy.email AS CreatedByEmail,
       ls.CreatedBy.displayname AS CreatedUserName,
       ls.ModifiedBy,
       ls.ModifiedBy.displayname AS ModifiedByUserName,
       ls.ModifiedBy.email AS ModifiedByEmail,
       ls.Modified,
       ls.Lsid,
       ls.ObjectId
FROM snd.LookupSets ls
